variable "vpc_id" {}
variable "cidr_blocks" {}
variable "oidc_url" {}
variable "account_id" {}
variable "aws_region" {}
variable "app_name" {}
variable "app_namespace" {}
variable "tfenv" {}
variable "base_cidr_block" {}
variable "billingcustomer" {}
variable "node_count" {}