exclude: (^examples/|archive/)
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.68.1
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terraform_validate
    - id: terraform_tflint