version: '3'

services:
  infra-terraform-eks:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/deploy/terraform_repo_eks/
    env_file:
      - .env
    environment:
      CI_PROJECT_DIR: /build
      AWS_DEFAULT_REGION: ap-southeast-1
      TF_VAR_app_name: eks
      TF_VAR_app_namespace: infra
      TF_VAR_tfenv: local-testing
      TF_VAR_instance_min_size: 1
      TF_VAR_instance_max_size: 2
      TF_VAR_instance_desired_size: 1
      TF_VAR_instance_type: t3a.medium
      TF_VAR_helm_installations: '{"vault_consul":false, "ingress":true}'
      CI_API_V4_URL: https://gitlab.com/api/v4
      TF_VAR_root_domain_name: tech.example.com
      TF_VAR_gitlab_namespace: TECHNOLOGY
      GITLAB_PROJECT_ID: 
      CI_PROJECT_ID: 
    command: export TF_ADDRESS=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${TF_VAR_app_name}-${TF_VAR_app_namespace}-${TF_VAR_tfenv} && \ 
             terraform init \
            -backend-config="address=${TF_ADDRESS}" \
            -backend-config="lock_address=${TF_ADDRESS}/lock" \
            -backend-config="unlock_address=${TF_ADDRESS}/lock" \
            -backend-config="username=${TF_VAR_gitlab_username}" \
            -backend-config="password=${TF_VAR_gitlab_token}" \
            -backend-config="lock_method=POST" \
            -backend-config="unlock_method=DELETE" \
            -backend-config="retry_wait_min=5"