apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: eks-primary-develop-service-account
    namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eks-primary-develop-service-account
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eks-primary-develop-service-account
roleRef:
  kind: Role
  name: eks-primary-develop-service-account
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: eks-primary-develop-service-account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eks-primary-develop-service-account
  namespace: default