# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

terraform {
  required_version = ">= 1.1.4, < 2.0"
  required_providers {
    kubernetes = {
      source = "hashicorp/kubernetes"
    }
    helm = {
      source = "hashicorp/helm"
    }
    twingate = {
      source = "Twingate/twingate"
    }
    kubectl = {
      source  = "alekc/kubectl"
      version = ">= 2.0.0"
    }
    random = {
      source  = "hashicorp/random"
    }
    postgresql = {
      source = "cyrilgdn/postgresql"
      version = ">= 1.19"
    }
    lacework = {
      source  = "lacework/lacework"
      version = "~> 1.0"
    }
  }
}
