config:
  clientID: "<Google Client ID>"
  clientSecret: "<Google Client Secret>"
  # Create a new cookieSecret with the following command
  # python -c 'import os,base64; print base64.b64encode(os.urandom(16))'
  cookieSecret: ".....EUapEdd77Qg=="
  configFile: |-
    pass_basic_auth = false
    pass_access_token = true
    set_authorization_header = true
    pass_authorization_header = true

image:
  repository: "quay.io/pusher/oauth2_proxy"
  #tag: "v3.1.0"
  tag: "latest"
  pullPolicy: "IfNotPresent"

extraArgs:
  provider: "google"
  email-domain: "magneticasia.com"
  #cookie-domain: ".ets-shared-uat1.tech.totalticketing.com"
  upstream: "file:///dev/null"
  http-address: "0.0.0.0:4180"